### ISSUE TITLE
Force apple updates/installs

### ISSUE THREAD

**Issue by maryniewskij** [google/simian#9]
I may need to post this in the Munki section, but I'm not sure.  I have 2 clients functioning.  I have updates that are supposed to be forced if they aren't installed but they don't seem to be installing.  Is it necessary for the user to open managed software center before you can have an update be installed?

**Comment by juofmgoblue** [comment]
Things to look at:
1) ensure the updates are enabled for the track(s) matching the clients.
2) regenerate the associated Software Update catalogs, or wait for that to happen automatically (based on any auto-promote schedule noted in the UI).
3) ensure that Munki is running regularly, and you've waited over 70 minutes since the change on the server.

Client logs should be telling.  And you should be able to inspect catalogs within /System/Library/Managed Installs/  (both the Software Update catalog and apple_update_metadata) to see if the updates and force install instructions are making their way to the client.   Let us know what you find...

**Comment by maryniewskij** [comment]
It was number 3, I didn't wait long enough for the updates to install.  Thanks!

PS: I'm also trying to restrict what users can log into my simian appspot site.  How can I restrict it to specified users? The only info I could find was from 2012 and before you guys moved to github.

**Comment by juofmgoblue** [comment]
https://github.com/google/simian/blob/master/src/simian/settings.py#L39

I think (for now at least) you want to toggle ALLOW_ALL_DOMAIN_USERS_READ_ACCESS to False, then add members you wish to grant access to groups in the admin UI, Admin Tools -> ACL Groups page.  This is, of course, assuming you've already restricted the app to your domain: https://github.com/google/simian/wiki/AdminSetup#obtain-an-app-engine-instance
